[project]
name = "desktop-organizer-mcp"
version = "0.1.0"
description = "MCP server for organizing files on Mac Desktop"
requires-python = ">=3.10"
dependencies = [
    "mcp>=0.1.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
